name: Update recent blog posts

on:
  schedule:
    # Runs every 4 hours
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update README with recent blog posts
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull recent blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@emellybmuniz"
          max_post_count: 3
          readme_path: "README.md"
          comment_tag_name: "BLOG-POST-LIST"
          template: |
            **[$title]($url)**  
            *Artigo no Medium* â€¢ Publicado em $date  
            $description
